// Synthetic operator settings shared by the isolated installation fixtures.
export const installationSettings = {
  PLATFORM_CONTROL_PLANE_IMAGE: "fixture/control-plane:latest",
  PLATFORM_SSO_IMAGE: "fixture/sso:latest",
  PLATFORM_AGENT_IMAGE: "fixture/agent:latest",
  PLATFORM_RUNTIME_IMAGE: "fixture/runtime:latest",
  PLATFORM_DATA_DIRECTORY: "/tmp/widefleet-installation-fixture",
  DOCKER_SOCKET_FILE: "/var/run/docker.sock",
  PLATFORM_URL: "https://platform.example.test",
  PLATFORM_USAGE_REPORTING: "false",
  PLATFORM_CRASH_REPORTING: "false",
  APP_DOMAIN: "apps.example.test",
  POSTGRES_PASSWORD: "fixture-only",
  DATABASE_URL:
    "postgres://fixture:fixture-only@database.example.test/platform?sslmode=verify-full",
  S3_ACCESS_KEY_ID: "fixture-storage",
  S3_SECRET_ACCESS_KEY: "fixture-storage-secret",
  AZURE_STORAGE_ACCOUNT_NAME: "fixtureaccount",
  AZURE_STORAGE_CONTAINER: "fixture-artifacts",
  FLEET_AZURE_CONTAINER: "fixture-fleets",
  GCS_BUCKET: "fixture-artifacts",
  FLEET_GCS_BUCKET: "fixture-fleets",
  BETTER_AUTH_SECRET: "fixture-secret-for-installation-tests-only",
  OAUTH2_PROXY_COOKIE_SECRET: "bG9jYWwtZGVtby1vbmx5LW5vdC1mb3ItcmVhbC11c2U=",
  ENTRA_TENANT_ID: "00000000-0000-4000-8000-000000000001",
  ENTRA_CLIENT_ID: "00000000-0000-4000-8000-000000000002",
  ENTRA_CLIENT_SECRET: "fixture-only",
  ENTRA_AUTHORITY: "http://127.0.0.1:1",
  APP_ENTRA_CLIENT_ID: "00000000-0000-4000-8000-000000000003",
  APP_ENTRA_CLIENT_SECRET: "fixture-only",
  ADMIN_ENTRA_OBJECT_IDS: "00000000-0000-4000-8000-000000000004",
  ACME_EMAIL: "operator@example.test",
  ACME_ENVIRONMENT: "staging",
  CLOUDFLARE_DNS_TOKEN_FILE: "/tmp/fixture-cloudflare-token",
};
